 export const GET_PRO_REQUEST = "GET_PRO_REQUEST"
 export const GET_PRO_SUCCESS = "GET_PRO_SUCCESS"
 export const GET_PRO_FAILURE = "GET_PRO_FAILURE"

 export const  ADD_CART_REQUEST = "ADD_CART_REQUEST" 
 export const  ADD_CART_SUCCESS =  "ADD_CART_SUCCESS"
 export const  ADD_CART_FAILURE = "ADD_CART_FAILURE"

 export const  GET_CART_REQUEST = "GET_CART_REQUEST" 
 export const  GET_CART_SUCCESS =  "GET_CART_SUCCESS"
 export const  GET_CART_FAILURE = "GET_CART_FAILURE"

 export const REMOVE_PRODUCT_CART_REQUEST = 'REMOVE_PRODUCT_CART_REQUEST';
export const REMOVE_PRODUCT_CART_SUCCESS = 'REMOVE_PRODUCT_CART_SUCCESS';
export const REMOVE_PRODUCT_CART_FAILURE = 'REMOVE_PRODUCT_CART_FAILURE';